#!/bin/sh

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functions   #
#############################

prefix_list="$prefix_list $DMROOT.Time."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_Time"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_Time"

entry_execute_method_root_Time() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.Time."*)
		common_execute_method_obj "$DMROOT.Time." "0"
		common_execute_method_param "$DMROOT.Time.NTPServer1" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.NTPServer2" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.CurrentLocalTime" "0" "echo TODO" "" "xsd:dateTime" "1"
		common_execute_method_param "$DMROOT.Time.LocalTimeZone" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.LocalTimeZoneName" "0" "get_timezone_name" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsUsed" "0" "echo TODO" "" "xsd:boolean" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsStart" "0" "echo TODO" "" "xsd:dateTime" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsEnd" "0" "echo TODO" "" "xsd:dateTime" "1"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################

get_timezone_name() {
	local tz=`timedatectl | grep 'Time zone'`
	tz=${tz#*'Time zone: '}
	echo $tz
}
