#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.Time."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_Time"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_Time"

entry_execute_method_root_Time() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.DeviceInfo."*)
		common_execute_method_obj "$DMROOT.Time." "0"
		common_execute_method_param "$DMROOT.Time.NTPServer1" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.NTPServer2" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.CurrentLocalTime" "0" "echo TODO" "" "xsd:dateTime" "1"
		common_execute_method_param "$DMROOT.Time.LocalTimeZone" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.LocalTimeZoneName" "0" "echo TODO" "" "xsd:string" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsUsed" "0" "echo TODO" "" "xsd:boolean" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsStart" "0" "echo TODO" "" "xsd:dateTime" "1"
		common_execute_method_param "$DMROOT.Time.DaylightSavingsEnd" "0" "echo TODO" "" "xsd:dateTime" "1"
		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}
