#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functions   #
#############################

prefix_list="$prefix_list $DMROOT.WANDevice."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_WANDevice"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform entry_execute_method_root_WANDevice"

entry_execute_method_root_WANDevice() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.WANDevice."*)
		common_execute_method_obj "$DMROOT.WANDevice." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionNumberOfEntries" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANCommonInterfaceConfig." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.EnabledForInternet" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.WANAccessType" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Layer1UpstreamMaxBitRate" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Layer1DownstreamMaxBitRate" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.PhysicalLinkStatus" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.WANAccessProvider" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.TotalBytesSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.TotalBytesReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.MaximumActiveConnections" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.NumberOfActiveConnections" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Connection." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Connection.1." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Connection.1.ActiveConnectionDeviceContainer" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANCommonInterfaceConfig.Connection.1.ActiveConnectionServiceID" "0" "echo TODO" "" "xsd:string"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Enable" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Status" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.MACAddress" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.MaxBitRate" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.DuplexMode" "0" "echo TODO" "" "xsd:string"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Stats." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Stats.BytesSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Stats.BytesReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Stats.PacketsSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANEthernetInterfaceConfig.Stats.PacketsReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnectionNumberOfEntries" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Enable" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionStatus" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PossibleConnectionTypes" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionType" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Name" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Uptime" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.LastConnectionError" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.RSIPAvailable" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.NATEnabled" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.AddressingType" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.SubnetMask" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DefaultGateway" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSEnabled" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSOverrideAllowed" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSServers" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MaxMTUSize" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddressOverride" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionTrigger" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.RouteProtocolRx" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMappingNumberOfEntries" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1" "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.PortMappingEnabled" "0" "echo TODO" "" "xsd:boolean"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.RemoteHost" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.ExternalPort" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.ExternalPortEndRange" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.InternalPort" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.PortMappingProtocol" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.InternalClient" "0" "echo TODO" "" "xsd:string"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.PortMappingDescription" "0" "echo TODO" "" "xsd:string"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsSent" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsReceived" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DHCPClient." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DHCPClient.SentDHCPOption." "0"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DHCPClient.ReqDHCPOption." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DHCPClient.ReqDHCPOptionNumberOfEntries" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DHCPClient.SentDHCPOptionNumberOfEntries" "0" "echo TODO" "" "xsd:unsignedInt"
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANEthernetLinkConfig." "0"
		common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.1.WANEthernetLinkConfig.EthernetLinkStatus" "0" "echo TODO" "" "xsd:string"
		local map maps=`wan_device_get_interface_maps` 
		for map in $maps; do
			local iface=${map%%:*}
			map=${map#*:}
			local j=${map%%:*}
			map=${map#*:}
			local protocol=${map%%:*}
			local default=${map#*:}
			sub_entry_wandevice_wanconnectiondevice "$1" "$j" "$iface" "$protocol" "$default"
		done
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

sub_entry_wandevice_wanconnectiondevice() {
	local j="$2"
	local iface="$3"
	local protocol="$4"
	local default="$5"
	case_param "$1" belongto "$DMROOT.WANDevice.1.WANConnectionDevice.$j." && {
		common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.$j." "0"
		case $protocol in
			IP)
			common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANIPConnection." "0"
			common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANIPConnection.1." "0"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANIPConnection.1.ConnectionStatus" "0" "wan_device_get_ipcx_status"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANIPConnection.1.ExternalIPAddress" "0" "wan_device_get_ipcx_ipaddr $iface" "" "" "$default"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANIPConnection.1.MACAddress" "0" "wan_device_get_ipcx_macaddr $iface"
			;;
			PPP)
			common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANPPPConnection." "0"
			common_execute_method_obj "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANPPPConnection.1." "0"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANPPPConnection.1.Enable" "1" "wan_device_get_ipcx_macaddr $iface" "wan_device_set_wan_ppp_enable $iface" "xsd:boolean"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANPPPConnection.1.Username" "1" "$UCI_GET network.$iface.username" "wan_device_set_wan_ppp_cfg network.$iface.username"
			common_execute_method_param "$DMROOT.WANDevice.1.WANConnectionDevice.$j.WANPPPConnection.1.Password" "1" "" "wan_device_set_wan_ppp_cfg network.$iface.password"
			;;
		esac
	}
}

#######################################
#   Data model parameters functions   #
#######################################

wan_device_get_interface_maps() {
	#should return a list like this: "<interface1>:<instance1>:<protocol>:<default interface? 1 : 0> <interface2>:<instance>:<protocol>:<default interface? 1 : 0>"
	echo "mng:1:IP:1 wan:2:PPP:0"
}

wan_device_get_ipcx_status() {
	echo "Connected"
}

wan_device_get_ipcx_ipaddr() {
	local val iface="$1"
	network_get_ipaddr val "$iface"
	echo "$val"
}

wan_device_get_ipcx_macaddr() {
	local val iface="$1"
	if [ -z "$default_wan_device_mng_interface_mac" ]; then
		val=`$UCI_GET network.$iface.macaddr`
	else
		val=$default_wan_device_mng_interface_mac
	fi
	echo $val
}

wan_device_get_wan_ppp_enable() {
	local iface="$1"
	local val=`$UCI_GET network.$iface.auto`
	echo ${val:-1}
}

wan_device_set_wan_ppp_enable() {
	local iface="$1"
	local val="$2"
	common_set_bool "network.$iface.auto" "$val" "1" "0"
	local e="$?"
	[ "$e" != "0" ] && return $e
	return 0
}

wan_device_set_wan_ppp_cfg() {
	local cfg="$1"
	local val="$2"
	$UCI_SET $cfg="$val"
	return 0
}
